feat: add icons for exchanges
ArkEcosystem/common pull request #7
Opened 2023-05-23 21:40 UTC by alfonsobries

## Summary

Related to https://app.clickup.com/t/861mruhvw

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

2023-05-23 21:56 UTC, alexbarnsley approved these changes

2023-05-23 21:58 UTC, alexbarnsley requested changes
the id's have been overwritten. e.g. `arkscan/icons/bingx.svg` has `id="a"`. you'll need to replace all these instances with `id="keep_whatevertheidis"`. if they all use the same they'll mess with each other when on the same page

2023-05-24 11:16 UTC, ItsANameToo requested changes
@alfonsobries there are still a couple SVGs that rely on short `ids` that need adjusting to avoid clashes, otherwise the `url` reference picks whatever is last and results in weird styles

2023-05-24 11:16 UTC, ItsANameToo commented on arkscan/icons/letsexchange.svg
> +<svg viewBox="0 0 20 21" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12.296 3.043c-.01.102-.68 5.164-.694 5.234-.012.07.019.189.19.189h2.902c.212 0 .164.185.063.315-.1.13-5.058 8.173-5.1
id

2023-05-24 11:16 UTC, ItsANameToo commented on arkscan/icons/bingx.svg
> +<svg viewBox="0 0 20 17" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8.615 5.751C5.465 10.748 1.744 11.446 0 11.342v4.66c2.872-.311 8.153-1.398 11.384-6.368 2.827-4.349 6.461-5.436 8.307
id

2023-05-24 11:16 UTC, ItsANameToo commented on arkscan/icons/bitexen.svg
> +<svg viewBox="0 0 19 14" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.85 14s8.052-8.067 9.105-9.105c1.053-1.039 2.988-1.31 3.983-.285.996 1.025 1.238 2.775.427 3.7-.81.924-1.138 1.294-1
id

2023-05-24 11:16 UTC, ItsANameToo commented on arkscan/icons/coinex.svg
> +<svg viewBox="0 0 19 21" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12.724 7.89a3.833 3.833 0 0 0-5.45 0c-1.508 1.533-1.492 4.03.015 5.563a3.823 3.823 0 0 0 5.467.016c.025-.026.131-.145
id

2023-05-24 11:16 UTC, ItsANameToo commented on arkscan/icons/coinspot.svg
> +<svg viewBox="0 0 21 21" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)"><path d="M20.005 9.877v.28c-.011.043-.002.086-.005.13v.134c0 .395-.038.787-.102 1.177a9.922 9.922 0 0 1-
id

2023-05-24 11:16 UTC, ItsANameToo commented on arkscan/icons/exodus.svg
> +<svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="m14 9.984 6 5.991h-2.125c-.375 0-.688-.125-.938-.374l-5.562-5.617 5.563-5.553c.25-.25.625-.375.937-.375H20l-6 5.928ZM3
id

2023-05-24 11:16 UTC, ItsANameToo commented on arkscan/icons/bitladon.svg
> +<svg viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)" fill="#454FBC"><path d="M11.624 9.917h.125a.791.791 0 0 0 .792-.792v-.75a.791.791 0 0 0-.792-.792H11V6.3
id

2023-05-24 16:07 UTC, alfonsobries commented
@ItsANameToo updated with a more unique id

2023-05-24 17:26 UTC, ItsANameToo approved these changes

2023-05-24 17:26 UTC, merged